apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nginx
  newName: nginx
  newTag: 1.29.1
resources:
- ../../base  # ⬅️ 이전에 문제가 되었던 '../base'를 '두 단계 상위'로 수정했습니다.
patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
