apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nginx
  newName: nginx
  newTag: 1.29.1
resources:
- base  # ⬅️ **'base' 디렉터리 자체가 아닌, 'kustomization.yaml' 파일을 명시합니다.**
patchesStrategicMerge:
- overlays/dev/deployment-patch.yaml
- overlays/dev/service-patch.yaml
