# base/kustomization.yaml 파일의 수정 내용

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nginx
  newName: nginx
  newTag: 1.27.1
resources:
- test-deployment.yaml  # ⬅️ 파일 이름 수정 (test- 접두사 추가)
- test-service.yaml     # ⬅️ 파일 이름 수정 (test- 접두사 추가)
- namespace.yam
